services:
  ldcode-ubuntu-setup-dev:
    build: 
      context: .
      dockerfile: .docker/Dockerfile.${DEV_MODE:-dev}
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION:-latest}
    container_name: ldcode-ubuntu-setup-dev
    tty: true
    stdin_open: true
    develop:
      watch:
        - action: rebuild
          path: ./setup.sh
          target: /usr/local/ldcode/ubuntu-setup/setup.sh