ARG UBUNTU_VERSION=latest

FROM ubuntu:${UBUNTU_VERSION}

# Set environment variables to noninteractive mode
ENV DEBIAN_FRONTEND=noninteractive

# Create /usr/local/ldcode directory if it doesn't exist
RUN mkdir -p /usr/local/ldcode/ubuntu-setup

# Copy the setup script
COPY setup.sh /usr/local/ldcode/ubuntu-setup/setup.sh
RUN chmod +x /usr/local/ldcode/ubuntu-setup/setup.sh

# Add command script to check installation
COPY ./check_installation.sh /usr/local/ldcode/ubuntu-setup/check_installation.sh
RUN chmod +x /usr/local/ldcode/ubuntu-setup/check_installation.sh

USER root

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD /bin/bash -c "/usr/local/ldcode/ubuntu-setup/setup.sh --all && /usr/local/ldcode/ubuntu-setup/check_installation.sh"
