ARG UBUNTU_VERSION=latest

FROM ubuntu:${UBUNTU_VERSION}

# Set environment variables to noninteractive mode
ENV DEBIAN_FRONTEND=noninteractive

# Create /usr/local/ldcode directory if it doesn't exist
RUN mkdir -p /usr/local/ldcode/ubuntu-setup

# Copy the setup script
COPY ./setup.sh /usr/local/ldcode/ubuntu-setup/setup.sh
RUN chmod +x /usr/local/ldcode/ubuntu-setup/setup.sh

# Add command script to check installation
COPY ./test/check_installation.sh /usr/local/ldcode/ubuntu-setup/check_installation.sh
RUN chmod +x /usr/local/ldcode/ubuntu-setup/check_installation.sh

COPY ./.docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh 

RUN apt-get update && apt-get install -y sudo

RUN useradd -ms /bin/bash ldcode && \
    echo 'ldcode ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
USER ldcode

ENTRYPOINT ["/entrypoint.sh"]

CMD /bin/bash -c "sudo -E /usr/local/ldcode/ubuntu-setup/setup.sh --all --vscode-extensions && /usr/local/ldcode/ubuntu-setup/check_installation.sh"
