---
- hosts: localhost
  become: yes

  tasks:
    - name: Check if snap is installed
      ansible.builtin.shell: "command -v snap"
      register: snap_check
      changed_when: false
      failed_when: false

    - name: Print snap installed
      ansible.builtin.debug:
        msg: "Snap is installed"
      when: snap_check.rc == 0
    
    - name: Print snap not installed
      ansible.builtin.debug:
        msg: "Snap is not installed"
      when: snap_check.rc != 0

    - name: Install Postman using snap
      ansible.builtin.command: snap install postman
      when: snap_check.rc == 0

    - name: Install necessary apt packages
      ansible.builtin.apt:
        name:
          - wget
          - tar
        state: present
      when: snap_check.rc != 0

    - name: Download Postman tar.gz
      ansible.builtin.get_url:
        url: https://dl.pstmn.io/download/latest/linux_64
        dest: /tmp/postman-linux-x64.tar.gz
        mode: '0644'
        force: true
      when: snap_check.rc != 0

    - name: Extract Postman
      ansible.builtin.unarchive:
        src: /tmp/postman-linux-x64.tar.gz
        dest: /opt
        remote_src: yes
      when: snap_check.rc != 0

    - name: Create symbolic link for Postman
      ansible.builtin.file:
        src: /opt/Postman/Postman
        dest: /usr/bin/postman
        state: link
      when: snap_check.rc != 0

    - name: Clean up
      ansible.builtin.file:
        path: /tmp/postman-linux-x64.tar.gz
        state: absent
      when: snap_check.rc != 0