name: CI

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck
    - name: Lint the scripts
      run: |
        shellcheck setup.sh

  test-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - name: Make scripts executable
      run: chmod +x setup.sh
    - name: Run setup script
      run: sudo ./setup.sh --all --set-warp-default
    - name: Check Docker installation
      run: |
        if ! command -v docker &> /dev/null; then
          echo "Docker not installed correctly"
          exit 1
        fi
        if ! docker compose version &> /dev/null; then
          echo "Docker Compose not installed correctly"
          exit 1
        fi
    - name: Check VS Code installation
      run: |
        if ! command -v code &> /dev/null; then
          echo "VS Code not installed correctly"
          exit 1
        fi
    - name: Check Warp Terminal installation
      run: |
        if ! command -v warp-terminal &> /dev/null; then
          echo "Warp Terminal not installed correctly"
          exit 1
        fi
